# vscode plugins
code --install-extension bierner.emojisense
code --install-extension dkundel.vscode-new-file
code --install-extension deiteris.vs-api-contractor
code --install-extension akamud.vscode-theme-onedark
code --install-extension bungcip.better-toml
code --install-extension dnicolson.binary-plist
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension alexkrenchik.cucumberauto
code --install-extension rokoroku.vscode-theme-darcula
code --install-extension fabiospampinato.vscode-diff
code --install-extension ms-azuretools.vscode-docker
code --install-extension mikestead.dotenv
code --install-extension dracula-theme.theme-dracula
code --install-extension editorconfig.editorconfig
code --install-extension grapecity.gc-excelview
code --install-extension foam.foam-vscode
code --install-extension waderyan.gitblame
code --install-extension donjayamanne.githistory
code --install-extension huizhou.githd
code --install-extension thenikso.github-plus-theme
code --install-extension github.vscode-pull-request-github
code --install-extension github.github-vscode-theme
code --install-extension golang.go
code --install-extension xmtt.go-mod-grapher
code --install-extension sainnhe.gruvbox-material
code --install-extension hashicorp.terraform
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension yzhang.markdown-all-in-one
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-footnotes
code --install-extension bierner.markdown-preview-github-style
code --install-extension bierner.markdown-mermaid
code --install-extension takumii.markdowntable
code --install-extension fabiospampinato.vscode-markdown-todo
code --install-extension marp-team.marp-vscode
code --install-extension pkief.material-icon-theme
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension sdras.night-owl
code --install-extension 42crunch.vscode-openapi
code --install-extension ryu1kn.partial-diff
code --install-extension xdebug.php-debug
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension jebbs.plantuml
code --install-extension pnp.polacode
code --install-extension esbenp.prettier-vscode
code --install-extension alefragnani.project-manager
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.python
code --install-extension mechatroner.rainbow-csv
code --install-extension blzjns.vscode-raml
code --install-extension redhat.vscode-commons
code --install-extension humao.rest-client
code --install-extension buenon.scratchpads
code --install-extension adpyke.vscode-sql-formatter
code --install-extension jock.svg
code --install-extension 4ops.terraform
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension vscodevim.vim
code --install-extension dougfinke.vscode-pandoc
code --install-extension zxh404.vscode-proto3
code --install-extension redhat.vscode-yaml
code --install-extension hilleer.yaml-plus-json
code --install-extension rickynormandeau.mariana-pro
